### ISSUE TITLE
Please create a new release from the last merge/commit so the scoring mechanism can be used

### ISSUE THREAD

**Issue by mccbryan3** [CrowdStrike/container-image-scan-action#10]

**Comment by shawndwells** [comment]
@mccbryan3 added the CrowdStrike/solution-architects group to have permissions. You should be able to do this now.

+cc @redhatrises: added the group as write access. Is this overkill?

**Comment by redhatrises** [comment]
There's more to releasing the action than just creating a "new release", the readme has to be updated to the version that will be created as well.

**Comment by shawndwells** [comment]
> There's more to releasing the action than just creating a "new release", the readme has to be updated to the version that will be created as well.

Yes. Once that process is documented, there are now many other people who can follow it & do a release :) Should be less burdensome for you.

**Comment by redhatrises** [comment]
Closing as release v0.4 was created.
